-- SQL para criação das tabelas no Supabase

CREATE TABLE public.doctors (
  id UUID NOT NULL DEFAULT gen_random_uuid(),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  nomeUser VARCHAR(50) NOT NULL,
  cpfUser BIGINT UNIQUE,
  dataNascUser DATE NOT NULL,
  emailUser VARCHAR(50),
  foneUser BIGINT,
  cepUser BIGINT,
  ufUser VARCHAR(2),
  cidadeUser VARCHAR(30),
  bairroUser VARCHAR(30),
  logradouroUser VARCHAR(50),
  numeroUser INTEGER,
  owner_id UUID NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (owner_id) REFERENCES auth.users (id) ON DELETE CASCADE,
  inserted_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

CREATE TABLE public.patients (
  id UUID NOT NULL DEFAULT gen_random_uuid(),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  nomepatient VARCHAR(50) NOT NULL,
  cpfpatient BIGINT UNIQUE,
  dataNascpatient DATE NOT NULL,
  emailpatient VARCHAR(50), 
  fonepatient BIGINT,
  ceppatient BIGINT,
  ufpatient VARCHAR(2),
  cidadepatient VARCHAR(30),
  bairropatient VARCHAR(30),
  logradouropatient VARCHAR(50),
  numeropatient INTEGER,
  PRIMARY KEY (id),
  inserted_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

CREATE TABLE public.consultations (
  id UUID NOT NULL DEFAULT gen_random_uuid(),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  patient_id UUID NOT NULL,
  doctor_id UUID NOT NULL,
  motivoconsultation VARCHAR(50),
  created_by UUID NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (created_by) REFERENCES auth.users (id) ON DELETE SET NULL,
  FOREIGN KEY (doctor_id) REFERENCES doctors (id) ON DELETE CASCADE,
  FOREIGN KEY (patient_id) REFERENCES patients (id) ON DELETE CASCADE,
  inserted_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

CREATE TABLE public.attendances (
  id UUID NOT NULL DEFAULT gen_random_uuid(),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  created_by UUID NULL,
  doctor_id UUID NOT NULL,
  patient_id UUID NOT NULL,
  consultation_id UUID NOT NULL,
  hist VARCHAR(2000),
  tipo VARCHAR(50) NOT NULL,
  taxMae VARCHAR(30),
  pesoMae REAL,
  estaturaMae REAL,
  paMae VARCHAR(20),
  tipoSangMae VARCHAR(3),
  tax VARCHAR(30),
  apgar1 VARCHAR(50),
  apgar5 VARCHAR(50),
  peso REAL,
  comprimento REAL,
  pc REAL,
  gesta INTEGER,
  para VARCHAR(20),
  cesareas INTEGER,
  abortos INTEGER,
  abotEspon INTEGER,
  vacinasMae VARCHAR(500),
  nascVivos INTEGER,
  mortNeo INTEGER,
  filhos INTEGER,
  intern BOOLEAN,
  cirg BOOLEAN,
  quantCirg INTEGER,
  consulPre BOOLEAN,
  quantConsulPre INTEGER,
  tratMae BOOLEAN,
  descrMae VARCHAR(300),
  PRIMARY KEY (id),
  FOREIGN KEY (created_by) REFERENCES auth.users (id) ON DELETE SET NULL,
  FOREIGN KEY (doctor_id) REFERENCES doctors (id) ON DELETE CASCADE,
  FOREIGN KEY (patient_id) REFERENCES patients (id) ON DELETE CASCADE,
  FOREIGN KEY (consultation_id) REFERENCES consultations (id) ON DELETE CASCADE,
  inserted_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);
